### ISSUE TITLE
Extract film name from directory even if it has _ 

### ISSUE THREAD

**Issue by utkarshbajaj** [utkarshbajaj/Find-IMDB-Ratings#1]
If the film name is star_wars_episode_one.mp4 the url ending generated should be star+wars+episode+one, right now this works for spaces only. (Eg. Star Wars works but star_wars doesn't)

**Comment by Vipul-Bajaj** [comment]
I can work on this, if not assigned.

**Comment by utkarshbajaj** [comment]
> I can work on this, if not assigned.

Sure

**Comment by imsaptarshi** [comment]
Can I work on this?

**Comment by utkarshbajaj** [comment]
> Can I work on this?

Just assigned someone, but I do have some more issues, pls watch if you want to.

**Comment by imsaptarshi** [comment]
I can't see anymore issues..

**Comment by utkarshbajaj** [comment]
> I can't see anymore issues..

I'll be putting them up in some time.
