### ISSUE TITLE
Sort the films. 

### ISSUE THREAD

**Issue by utkarshbajaj** [utkarshbajaj/Find-IMDB-Ratings#2]
Sort the films according to the ratings, the maximum rated film should be at the top and then store it in the .csv file.

**Comment by termdew** [comment]
I'd like to work on this!

**Comment by ddebrup** [comment]
Is it open, can I work on this?

**Comment by sarthak55k** [comment]
Can i work on this?

**Comment by utkarshbajaj** [comment]
> I'd like to work on this!

Sure, go ahead.
